@startuml
'https://plantuml.com/sequence-diagram

autonumber

Actor -> UploadInteractor : execute
UploadInteractor -> API_Call : transcribe
API_Call --> UploadInteractor
UploadInteractor -> EpisodeFactory : create
EpisodeFactory --> UploadInteractor
UploadInteractor -> EpisodeDataAccessInterface : save
EpisodeDataAccessInterface --> UploadInteractor
UploadInteractor -> EpisodeOutputData : <<create>>
EpisodeOutputData --> UploadInteractor
UploadInteractor -> EpisodeOutputBoundary : prepareSuccessView
@enduml