@startuml
mainframe uploadPodast

autonumber

Actor -> EpisodeView : uploadPodcast
EpisodeView -> EpisodeController : execute
EpisodeController -> EpisodeInputData : <<create>>
return EpisodeInputData
EpisodeController -> EpisodeInputBoundary : execute
return

EpisodeController --> EpisodeView

@enduml